import 'dart:typed_data';

import 'package:pdf/widgets.dart';

import '../utils.dart';

class PdfService {
  static PdfTextStyles? styles;

  static Future<void> init() async {
    try {
      styles ??= await PdfTextStyles.init();
    } catch (e, t) {
      AppLogger.severe("$e", error: e, stackTrace: t);
    }
  }

  static Future<Uint8List?> pdfFromSections(PdfTranscript transcript) async {
    try {
      final title = transcript.title;
      final subTitle = transcript.subTitle;
      final plainText = transcript.plainText;
      final isProUser = transcript.isProUser;
      final sections = transcript.sections ?? [];

      if (!sections.hasValue && !plainText.hasValue) return null;
      final pdf = Document(title: title, author: "transcribr.org");
      styles ??= await PdfTextStyles.init();

      pdf.addPage(
        MultiPage(
          pageTheme: const PageTheme(
            margin: EdgeInsets.symmetric(vertical: 40, horizontal: 20),
          ),
          maxPages: 1000,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          footer: (context) {
            if (isProUser) return SizedBox.shrink();
            return Link(
              child: Text("Generated by transcribr.org"),
              destination: "https://app.transcribr.org",
            );
          },
          build: (context) {
            return [
              if (!isProUser) ...[
                PdfSvg(alignment: Alignment.topLeft),
                SizedBox(height: 40),
              ],
              Text(
                title,
                style: styles?.t3(),
                textDirection: title.pdfDirectionality,
              ),
              SizedBox(height: 2),
              Text(
                subTitle,
                style: styles?.body(color: AppPdfColors.secondaryTextColor),
                textDirection: subTitle.pdfDirectionality,
              ),
              SizedBox(height: 30),
              PdfTitle("Plain Text", textStyle: styles!),
              SizedBox(height: 10),
              PdfText(plainText, textStyle: styles!),
              SizedBox(height: 30),
              if (sections.hasValue) ...[
                PdfTitle("Sections", textStyle: styles!),
                SizedBox(height: 10),
                ListView.separated(
                  itemBuilder: (_, index) {
                    final section = sections[index];
                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        if (section.header.hasValue ||
                            section.headerTrailing.hasValue) ...[
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Expanded(
                                child: PdfSubtitle(
                                  section.header ?? "",
                                  textStyle: styles!,
                                ),
                              ),
                              if (section.headerTrailing.hasValue)
                                Text(
                                  section.headerTrailing!.capitalise(),
                                  style: styles?.button1(),
                                  textDirection:
                                      section.headerTrailing.pdfDirectionality,
                                ),
                            ],
                          ),
                          SizedBox(height: 6),
                        ],
                        PdfText(section.text, textStyle: styles!),
                      ],
                    );
                  },
                  separatorBuilder: (_, __) => SizedBox(height: 10),
                  itemCount: sections.length,
                ),
              ],
            ];
          },
        ),
      );

      return await pdf.save();
    } catch (e, t) {
      AppLogger.severe("$e", error: e, stackTrace: t);
      rethrow;
    }
  }

  static Future<Uint8List?> pdfForSummary(
    PdfTranscriptSummary summary,
  ) async {
    try {
      styles ??= await PdfTextStyles.init();
      final pdf = Document(title: summary.title, author: "transcribr.org")
        ..addPage(
          MultiPage(
            pageTheme: const PageTheme(
              margin: EdgeInsets.symmetric(vertical: 40, horizontal: 20),
            ),
            maxPages: 1000,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            footer: (context) {
              if (summary.isProUser) return SizedBox.shrink();
              return Link(
                child: Text("Generated by transcribr.org"),
                destination: "https://app.transcribr.org",
              );
            },
            build: (context) {
              return [
                if (!summary.isProUser) ...[
                  SvgImage(svg: logo, alignment: Alignment.topLeft),
                  SizedBox(height: 40),
                ],
                Text(
                  summary.title,
                  style: styles?.t3(),
                  textAlign: TextAlign.start,
                  textDirection: summary.title.pdfDirectionality,
                ),
                SizedBox(height: 2),
                Text(
                  summary.duration,
                  style: styles?.body(color: AppPdfColors.secondaryTextColor),
                  textAlign: TextAlign.start,
                ),
                SizedBox(height: 30),
                if (summary.quickSummary.hasValue) ...[
                  PdfTranscriptQuickSummaryCard(
                    quickSummary: summary.quickSummary,
                    textStyle: styles!,
                  ),
                  SizedBox(height: 24),
                ],
                if (summary.summaryOverview.hasValue) ...[
                  PdfTitle(
                    "Summary Overview",
                    textStyle: styles!,
                  ),
                  SizedBox(height: 10),
                  PdfText(
                    summary.summaryOverview!,
                    textStyle: styles!,
                  ),
                  SizedBox(height: 24),
                ],
                if (summary.keyTopics.hasValue) ...[
                  PdfTitle(
                    "Key Topics & Brief Explanations",
                    textStyle: styles!,
                  ),
                  SizedBox(height: 10),
                  for (final topic in summary.keyTopics!) ...[
                    PdfSubtitle(topic.topic.value, textStyle: styles!),
                    SizedBox(height: 8),
                    PdfText(topic.explanation.value, textStyle: styles!),
                  ],
                  SizedBox(height: 24),
                ],
                if (summary.decisionsAndFindings.hasValue) ...[
                  PdfTitle(
                    "Decisions & Findings",
                    textStyle: styles!,
                  ),
                  SizedBox(height: 10),
                  PdfText(
                    summary.decisionsAndFindings!,
                    textStyle: styles!,
                  ),
                  SizedBox(height: 24),
                ],
                if (summary.actionableTakeaways.hasValue) ...[
                  PdfTitle(
                    "Actionable Takeaways",
                    textStyle: styles!,
                  ),
                  SizedBox(height: 10),
                  for (final line in summary.actionableTakeaways!)
                    PdfTextTile(line, textStyle: styles!),
                  SizedBox(height: 24),
                ],
                if (summary.participants.hasValue) ...[
                  PdfTitle("Participants", textStyle: styles!),
                  SizedBox(height: 10),
                  for (final line in summary.participants!)
                    PdfTextTile(line, textStyle: styles!),
                  SizedBox(height: 24),
                ],
              ];
            },
          ),
        );

      return await pdf.save();
    } catch (e, t) {
      AppLogger.severe("$e", error: e, stackTrace: t);
      return null;
    }
  }
}
