import 'package:pdf/widgets.dart';

import '../../utils.dart';

class PdfProFooter extends StatelessWidget {
  final PdfTextStyles textStyle;

  PdfProFooter({required this.textStyle});

  @override
  Widget build(Context context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Link(
          child: Text(
            "Generated by transcribr.org",
            style: textStyle.callout(color: AppPdfColors.primaryTextColor),
          ),
          destination: "https://app.transcribr.org",
        ),
        Spacer(),
        Link(
          child: Text(
            "Go Pro to remove watermark",
            style: textStyle.callout(color: AppPdfColors.primaryTextColor),
          ),
          destination: "https://app.transcribr.org/dashboard/subscription",
        ),
      ],
    );
  }
}
